package com.inscription.spring.bean.enums;

public enum CountryEnum{
	
	  Afghanistan ("Afghanistan"),
	  AlandIslands ("Aland Islands"),
	  Albania ("Albania"),
	  Algeria ("Algeria"),
	  AmericanSamoa ("American Samoa"),
	  Andorra ("Andorra"),
	  Angola ("Angola"),
	  Anguilla ("Anguilla"),
	  Antarctica ("Antarctica"),
	  AntiguaandBarbuda ("Antigua and Barbuda"),
	  Argentina ("Argentina"),
	  Armenia ("Armenia"),
	  Aruba ("Aruba"),
	  Australia ("Australia"),
	  Austria ("Austria"),
	  Azerbaijan ("Azerbaijan"),
	  Bahamas ("Bahamas"),
	  Bahrain ("Bahrain"),
	  BakerIsland ("Baker Island"),
	  Bangladesh ("Bangladesh"),
	  Barbados ("Barbados"),
	  Belarus ("Belarus"),
	  Belgium ("Belgium"),
	  Belize ("Belize"),
	  Benin ("Benin"),
	  Bermuda ("Bermuda"),
	  Bhutan ("Bhutan"),
	  Bolivia ("Bolivia"),
	  BonairSaintEustachiusandSaba ("Bonair, Saint Eustachius and Saba"),
	  BosniaandHerzegovina ("Bosnia and Herzegovina"),
	  Botswana ("Botswana"),
	  BouvetIsland ("Bouvet Island"),
	  Brazil ("Brazil"),
	  BritishIndianOceanTerritory ("British Indian Ocean Territory"),
	  BritishVirginIslands ("British Virgin Islands"),
	  Brunei ("Brunei"),
	  Bulgaria ("Bulgaria"),
	  BurkinaFaso ("Burkina Faso"),
	  Burundi ("Burundi"),
	  Cambodia ("Cambodia"),
	  Cameroon ("Cameroon"),
	  Canada ("Canada"),
	  CapeVerde ("Cape Verde"),
	  CaymanIslands ("Cayman Islands"),
	  CentralAfricanRepublic ("Central African Republic"),
	  Chad ("Chad"),
	  Chile ("Chile"),
	  China ("China"),
	  ChristmasIsland ("Christmas Island"),
	  CocosIslands ("Cocos (Keeling) Islands"),
	  Colombia ("Colombia"),
	  Comoros ("Comoros"),
	  CookIslands ("Cook Islands"),
	  CostaRica ("Costa Rica"),
	  CotedIvoire ("Côte d'Ivoire"),
	  Croatia ("Croatia"),
	  Cuba ("Cuba"),
	  Curacao ("Curaçao"),
	  Cyprus ("Cyprus"),
	  Czechia ("Czechia"),
	  DemocraticRepublicofCongo ("Democratic Republic of Congo"),
	  Denmark ("Denmark"),
	  Djibouti ("Djibouti"),
	  Dominica ("Dominica"),
	  DominicanRepublic ("Dominican Republic"),
	  Ecuador ("Ecuador"),
	  Egypt ("Egypt"),
	  ElSalvador ("El Salvador"),
	  EquatorialGuinea ("Equatorial Guinea"),
	  Eritrea ("Eritrea"),
	  Estonia ("Estonia"),
	  Eswatini ("Eswatini"),
	  Ethiopia ("Ethiopia"),
	  FalklandIslands ("Falkland Islands"),
	  FaroeIslands ("Faroe Islands"),
	  FederatedStatesofMicronesia ("Federated States of Micronesia"),
	  Fiji ("Fiji"),
	  Finland ("Finland"),
	  France ("France"),
	  FrenchGuiana ("French Guiana"),
	  FrenchPolynesia ("French Polynesia"),
	  FrenchSouthernandAntarcticLands ("French Southern and Antarctic Lands"),
	  Gabon ("Gabon"),
	  Gambia ("Gambia"),
	  Georgia ("Georgia"),
	  Germany ("Germany"),
	  Ghana ("Ghana"),
	  Gibraltar ("Gibraltar"),
	  GloriosoIslands ("Glorioso Islands"),
	  Greece ("Greece"),
	  Greenland ("Greenland"),
	  Grenada ("Grenada"),
	  Guadeloupe ("Guadeloupe"),
	  Guam ("Guam"),
	  Guatemala ("Guatemala"),
	  Guernsey ("Guernsey"),
	  Guinea ("Guinea"),
	  GuineaBissau ("Guinea-Bissau"),
	  Guyana ("Guyana"),
	  Haiti ("Haiti"),
	  HeardIslandandMcDonaldIslands ("Heard Island and McDonald Islands"),
	  Honduras ("Honduras"),
	  HongKong ("Hong Kong"),
	  HowlandIsland ("Howland Island"),
	  Hungary ("Hungary"),
	  Iceland ("Iceland"),
	  India ("India"),
	  Indonesia ("Indonesia"),
	  Iran ("Iran"),
	  Iraq ("Iraq"),
	  Ireland ("Ireland"),
	  IsleofMan ("Isle of Man"),
	  Israel ("Israel"),
	  Italy ("Italy"),
	  Jamaica ("Jamaica"),
	  Japan ("Japan"),
	  JarvisIsland ("Jarvis Island"),
	  Jersey ("Jersey"),
	  JohnstonAtoll ("Johnston Atoll"),
	  Jordan ("Jordan"),
	  JuanDeNovaIsland ("Juan De Nova Island"),
	  Kazakhstan ("Kazakhstan"),
	  Kenya ("Kenya"),
	  Kiribati ("Kiribati"),
	  Kosovo ("Kosovo"),
	  Kuwait ("Kuwait"),
	  Kyrgyzstan ("Kyrgyzstan"),
	  LaoPeoplesDemocraticRepublic ("Lao People's Democratic Republic"),
	  Latvia ("Latvia"),
	  Lebanon ("Lebanon"),
	  Lesotho ("Lesotho"),
	  Liberia ("Liberia"),
	  Libya ("Libya"),
	  Liechtenstein ("Liechtenstein"),
	  Lithuania ("Lithuania"),
	  Luxembourg ("Luxembourg"),
	  Macau ("Macau"),
	  Madagascar ("Madagascar"),
	  Malawi ("Malawi"),
	  Malaysia ("Malaysia"),
	  Maldives ("Maldives"),
	  Mali ("Mali"),
	  Malta ("Malta"),
	  MarshallIslands ("Marshall Islands"),
	  Martinique ("Martinique"),
	  Mauritania ("Mauritania"),
	  Mauritius ("Mauritius"),
	  Mayotte ("Mayotte"),
	  Mexico ("Mexico"),
	  MidwayIslands ("Midway Islands"),
	  Moldova ("Moldova"),
	  Monaco ("Monaco"),
	  Mongolia ("Mongolia"),
	  Montenegro ("Montenegro"),
	  Montserrat ("Montserrat"),
	  Morocco ("Morocco"),
	  Mozambique ("Mozambique"),
	  Myanmar ("Myanmar"),
	  Namibia ("Namibia"),
	  Nauru ("Nauru"),
	  Nepal ("Nepal"),
	  Netherlands ("Netherlands"),
	  NewCaledonia ("New Caledonia"),
	  NewZealand ("New Zealand"),
	  Nicaragua ("Nicaragua"),
	  Niger ("Niger"),
	  Nigeria ("Nigeria"),
	  Niue ("Niue"),
	  NorfolkIsland ("Norfolk Island"),
	  NorthKorea ("North Korea"),
	  NorthMacedonia ("North Macedonia"),
	  NorthernMarianaIslands ("Northern Mariana Islands"),
	  Norway ("Norway"),
	  Oman ("Oman"),
	  Pakistan ("Pakistan"),
	  Palau ("Palau"),
	  PalestinianTerritories ("Palestinian Territories"),
	  Panama ("Panama"),
	  PapuaNewGuinea ("Papua New Guinea"),
	  Paraguay ("Paraguay"),
	  Peru ("Peru"),
	  Philippines ("Philippines"),
	  PitcairnIslands ("Pitcairn Islands"),
	  Poland ("Poland"),
	  Portugal ("Portugal"),
	  PuertoRico ("Puerto Rico"),
	  Qatar ("Qatar"),
	  RepublicofCongo ("Republic of Congo"),
	  Reunion ("Reunion"),
	  Romania ("Romania"),
	  Russia ("Russia"),
	  Rwanda ("Rwanda"),
	  SaintBarthelemy ("Saint Barthelemy"),
	  SaintHelena ("Saint Helena"),
	  SaintKittsandNevis ("Saint Kitts and Nevis"),
	  SaintLucia ("Saint Lucia"),
	  SaintMartin ("Saint Martin"),
	  SaintPierreandMiquelon ("Saint Pierre and Miquelon"),
	  SaintVincentandtheGrenadines ("Saint Vincent and the Grenadines"),
	  Samoa ("Samoa"),
	  SanMarino ("San Marino"),
	  SaoTomeandPrincipe ("Sao Tome and Principe"),
	  SaudiArabia ("Saudi Arabia"),
	  Senegal ("Senegal"),
	  Serbia ("Serbia"),
	  Seychelles ("Seychelles"),
	  SierraLeone ("Sierra Leone"),
	  Singapore ("Singapore"),
	  SintMaarten ("Sint Maarten"),
	  Slovakia ("Slovakia"),
	  Slovenia ("Slovenia"),
	  SolomonIslands ("Solomon Islands"),
	  Somalia ("Somalia"),
	  SouthAfrica ("South Africa"),
	  SouthGeorgiaandSouthSandwichIslands ("South Georgia and South Sandwich Islands"),
	  SouthKorea ("South Korea"),
	  SouthSudan ("South Sudan"),
	  Spain ("Spain"),
	  SriLanka ("Sri Lanka"),
	  Sudan ("Sudan"),
	  Suriname ("Suriname"),
	  SvalbardandJanMayen ("Svalbard and Jan Mayen"),
	  Sweden ("Sweden"),
	  Switzerland ("Switzerland"),
	  Syria ("Syria"),
	  Taiwan ("Taiwan"),
	  Tajikistan ("Tajikistan"),
	  Tanzania ("Tanzania"),
	  Thailand ("Thailand"),
	  TimorLeste ("Timor-Leste"),
	  Togo ("Togo"),
	  Tokelau ("Tokelau"),
	  Tonga ("Tonga"),
	  TrinidadandTobago ("Trinidad and Tobago"),
	  Tunisia ("Tunisia"),
	  Turkey ("Turkey"),
	  Turkmenistan ( "Turkmenistan"),
	  TurksandCaicosIslands ("Turks and Caicos Islands"),
	  Tuvalu ("Tuvalu"),
	  Uganda ("Uganda"),
	  Ukraine ( "Ukraine"),
	  UnitedArabEmirates ("United Arab Emirates"),
	  UnitedKingdom ("United Kingdom"),
	  UnitedStates ( "United States"),
	  Uruguay ("Uruguay"),
	  USVirginIslands ( "US Virgin Islands"),
	  Uzbekistan ("Uzbekistan"),
	  Vanuatu ("Vanuatu"),
	  VaticanCity ("Vatican City"),
	  Venezuela ("Venezuela"),
	  Vietnam ("Vietnam"),
	  WakeIsland ("Wake Island"),
	  WallisandFutuna ("Wallis and Futuna"),
	  WesternSahara ("Western Sahara"),
	  Yemen ("Yemen"),
	  Zambia ("Zambia"),
	  Zimbabwe ("Zimbabwe");

	private String name = "";

	CountryEnum(String name) {
		this.name = name;
	}

    public String getName() {
        return this.name;
    }

}
